### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by bibinmjose** [jtpio/pixijs-jupyter#1]
Hi Jeremy,

I tried `pip install -e .` from repo's `/root` and found this error. Is there a work around?

Thanks a lot
```
ValueError: missing files: 
['/home/<username>/Documents/jupyter-lab_tutorials/pixijs-jupyter/ipyutils/nbextension/static/index.js',
 '/home/<username>/Documents/jupyter-lab_tutorials/pixijs-jupyter/lib/plugin.js']
```

**Comment by bibinmjose** [comment]
Closing this issue. Installing nodejs and npm on the system fixed this issue

**Comment by jtpio** [comment]
Thanks for the report @bibinmjose !

We should add a set of requirements to the README file, such as:
- node 9 max (for now, until https://github.com/jupyterlab/jupyterlab/issues/4986 is fixed)
- npm
- jupyterlab
- ipywidgets

Or just mention to first create a virtual environment using https://github.com/jtpio/pixijs-jupyter/blob/master/binder/environment.yml

**Comment by jtpio** [comment]
README updated with https://github.com/jtpio/pixijs-jupyter/commit/31440bc39e87c13f05eec8ee56e0618eabcb3939
